# Generated by Django 5.2.1 on 2026-05-18 00:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'competition',
            },
        ),
        migrations.CreateModel(
            name='CompetitionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Period 1'", max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('freeze_datetime', models.DateTimeField(blank=True, help_text="When this period's scores lock. Defaults to end of end_date if blank.", null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='metrics.competition')),
            ],
            options={
                'db_table': 'competition_period',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='SectionPeriodScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_members', models.PositiveSmallIntegerField(help_text='Members in the section at freeze time.')),
                ('participating_members', models.PositiveSmallIntegerField(help_text='Members with at least one activity minute in this period.')),
                ('total_member_points', models.FloatField(help_text='Sum of per-member computed points for this period.', validators=[django.core.validators.MinValueValidator(0)])),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_scores', to='metrics.competitionperiod')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_scores', to='members.section')),
            ],
            options={
                'verbose_name': 'Section Period Score',
                'verbose_name_plural': 'Section Period Scores',
                'db_table': 'section_period_score',
                'permissions': [('can_freeze_period_scores', 'Can freeze Section Period Scores')],
                'constraints': [models.UniqueConstraint(fields=('section', 'period'), name='unique_section_period')],
            },
        ),
    ]
