# Generated by Django 5.2.1 on 2026-05-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionperiodscore',
            name='rank_score',
            field=models.FloatField(blank=True, default=None, help_text='Rank points earned at end of period (average of tied positions).', null=True),
        ),
    ]
