# Generated by Django 5.2.3 on 2025-06-29 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberweeklypoints',
            options={'verbose_name': 'Member Weekly Points', 'verbose_name_plural': 'Member Weekly Points'},
        ),
        migrations.AlterModelOptions(
            name='sectionweeklyscore',
            options={'verbose_name': 'Section Weekly Score', 'verbose_name_plural': 'Section Weekly Scores'},
        ),
        migrations.AlterField(
            model_name='sectionweeklyscore',
            name='rank_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
