# Generated by Django 5.2.3 on 2025-07-04 19:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_section_slug'),
        ('metrics', '0002_alter_memberweeklypoints_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberweeklypoints',
            name='minutes',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10080)]),
        ),
        migrations.AlterField(
            model_name='sectionweeklyscore',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_scores', to='members.section'),
        ),
        migrations.AddConstraint(
            model_name='memberweeklypoints',
            constraint=models.UniqueConstraint(fields=('member', 'week'), name='unique_member_week'),
        ),
        migrations.AddConstraint(
            model_name='sectionweeklyscore',
            constraint=models.UniqueConstraint(fields=('section', 'week'), name='unique_section_week'),
        ),
        migrations.AddConstraint(
            model_name='sectionweeklyscore',
            constraint=models.UniqueConstraint(fields=('week', 'rank_score'), name='unique_week_rank'),
        ),
    ]
