# Generated by Django 5.2.1 on 2025-07-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_alter_memberweeklypoints_minutes_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='memberweeklypoints',
            table='member_weekly_points',
        ),
        migrations.AlterModelTable(
            name='sectionweeklyscore',
            table='section_weekly_score',
        ),
    ]
