# Generated by Django 5.2.1 on 2025-07-18 21:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_member_table_alter_memberpreferences_table_and_more'),
        ('metrics', '0004_alter_memberweeklypoints_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberweeklypoints',
            name='points',
            field=models.FloatField(default=0.0, editable=False, help_text="A member's point total for the week, calculated from their weekly minutes.", validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memberweeklypoints',
            name='member',
            field=models.ForeignKey(help_text='The associated member that the weekly points are for.', on_delete=django.db.models.deletion.CASCADE, related_name='weekly_points', to='members.member'),
        ),
        migrations.AlterField(
            model_name='memberweeklypoints',
            name='minutes',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='The total number of minutes that the member completed in the given week.', validators=[django.core.validators.MaxValueValidator(10080)]),
        ),
        migrations.AlterField(
            model_name='memberweeklypoints',
            name='week',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4'), (5, 'Week 5'), (6, 'Week 6'), (7, 'Week 7'), (8, 'Week 8')], help_text='The week in which the points were earned.'),
        ),
        migrations.AlterField(
            model_name='sectionweeklyscore',
            name='participating_members',
            field=models.PositiveSmallIntegerField(help_text='The number of participating members in the section for this week. Participation means being registered and having completed activity minutes.'),
        ),
        migrations.AlterField(
            model_name='sectionweeklyscore',
            name='rank_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text="A score from 1-12 giving the section's rank among other sections for this week.", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='sectionweeklyscore',
            name='section',
            field=models.ForeignKey(help_text='The associated section that the weekly score is for.', on_delete=django.db.models.deletion.CASCADE, related_name='weekly_scores', to='members.section'),
        ),
        migrations.AlterField(
            model_name='sectionweeklyscore',
            name='total_member_points',
            field=models.FloatField(help_text='The total number of points earned by all members in the section for this week.'),
        ),
        migrations.AlterField(
            model_name='sectionweeklyscore',
            name='total_members',
            field=models.PositiveSmallIntegerField(help_text='The total number of members in the section for this week.'),
        ),
        migrations.AlterField(
            model_name='sectionweeklyscore',
            name='week',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4'), (5, 'Week 5'), (6, 'Week 6'), (7, 'Week 7'), (8, 'Week 8')], help_text='The week in which the score was calculated.'),
        ),
    ]
