# Generated by Django 5.2.1 on 2025-07-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_memberweeklypoints_points_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionweeklyscore',
            options={'permissions': [('can_recompute_sws', 'Can recompute Section Weekly Scores')], 'verbose_name': 'Section Weekly Score', 'verbose_name_plural': 'Section Weekly Scores'},
        ),
    ]
