# Generated by Django 5.2.1 on 2025-06-27 15:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SectionWeeklyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('total_members', models.PositiveSmallIntegerField()),
                ('participating_members', models.PositiveSmallIntegerField()),
                ('total_member_points', models.FloatField()),
                ('rank_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_points', to='sections.section')),
            ],
        ),
    ]
