# Generated by Django 5.2.3 on 2025-06-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.BigIntegerField()),
                ('member_id', models.BigIntegerField()),
                ('event_time', models.DateTimeField()),
                ('processed', models.BooleanField()),
            ],
        ),
    ]
