# Generated by Django 5.2.3 on 2025-06-29 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebhookEvent',
        ),
    ]
