# Generated by Django 5.2.1 on 2026-05-18 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.BigIntegerField(help_text='The Strava activity ID for the activity.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="The name of the activity (e.g., 'Morning Run').", max_length=255)),
                ('distance', models.FloatField(blank=True, default=0, help_text='The distance (in miles) of the activity (if applicable).')),
                ('minutes', models.IntegerField(blank=True, default=0, help_text='The duration of the activity, in minutes.')),
                ('elapsed_time', models.IntegerField(blank=True, default=0, help_text='The total elapsed time of the activity, in minutes. Includes pauses.')),
                ('elevation_gain', models.FloatField(blank=True, default=0, help_text='The total elevation gain of the activity, in feet (if applicable).')),
                ('sport_type', models.CharField(choices=[('AlpineSki', 'Alpine Ski'), ('BackcountrySki', 'Backcountry Ski'), ('Badminton', 'Badminton'), ('Canoeing', 'Canoeing'), ('Crossfit', 'Crossfit'), ('EBikeRide', 'E-Bike Ride'), ('Elliptical', 'Elliptical'), ('EMountainBikeRide', 'E-Mountain Bike Ride'), ('Golf', 'Golf'), ('GravelRide', 'Gravel Ride'), ('Handcycle', 'Handcycle'), ('HighIntensityIntervalTraining', 'High Intensity Interval Training'), ('Hike', 'Hike'), ('IceSkate', 'Ice Skate'), ('InlineSkate', 'Inline Skate'), ('Kayaking', 'Kayaking'), ('Kitesurf', 'Kitesurf'), ('MountainBikeRide', 'Mountain Bike Ride'), ('NordicSki', 'Nordic Ski'), ('Pickleball', 'Pickleball'), ('Pilates', 'Pilates'), ('Racquetball', 'Racquetball'), ('Ride', 'Ride'), ('RockClimbing', 'Rock Climbing'), ('RollerSki', 'Roller Ski'), ('Rowing', 'Rowing'), ('Run', 'Run'), ('Sail', 'Sail'), ('Skateboard', 'Skateboard'), ('Snowboard', 'Snowboard'), ('Snowshoe', 'Snowshoe'), ('Soccer', 'Soccer'), ('Squash', 'Squash'), ('StairStepper', 'Stair Stepper'), ('StandUpPaddling', 'Stand Up Paddling'), ('Surfing', 'Surfing'), ('Swim', 'Swim'), ('TableTennis', 'Table Tennis'), ('Tennis', 'Tennis'), ('TrailRun', 'Trail Run'), ('Velomobile', 'Velomobile'), ('VirtualRide', 'Virtual Ride'), ('VirtualRow', 'Virtual Row'), ('VirtualRun', 'Virtual Run'), ('Walk', 'Walk'), ('WeightTraining', 'Weight Training'), ('Wheelchair', 'Wheelchair'), ('Windsurf', 'Windsurf'), ('Workout', 'Workout'), ('Yoga', 'Yoga')], help_text='The type of activity (e.g., Run, Ride, Walk).', max_length=50)),
                ('datetime', models.DateTimeField(help_text='The date and time that the activity started.')),
                ('polyline', models.TextField(blank=True, default='', help_text='The encoded polyline representing the GPS route (if applicable).')),
                ('manual', models.BooleanField(help_text='Whether the activity was entered manually.')),
                ('private', models.BooleanField(help_text='Whether the activity is marked as private.')),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='activity_maps/')),
                ('svg_path', models.TextField(blank=True, default='', help_text='SVG path d attribute derived from the encoded polyline, for art visualization.')),
                ('member', models.ForeignKey(help_text='The member that the activity belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='members.member')),
                ('period', models.ForeignKey(blank=True, help_text='The competition period this activity falls within.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='metrics.competitionperiod')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'activity',
                'ordering': ['-datetime'],
            },
        ),
    ]
