# Generated by Django 5.2.1 on 2025-06-16 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0004_alter_stravaauth_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('distance', models.FloatField(blank=True, default=0)),
                ('minutes', models.IntegerField(blank=True, default=0)),
                ('elapsed_time', models.IntegerField(blank=True, default=0)),
                ('elevation_gain', models.FloatField(blank=True, default=0)),
                ('type', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('polyline', models.TextField()),
                ('manual', models.BooleanField()),
                ('private', models.BooleanField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='members.member')),
            ],
        ),
    ]
