# Generated by Django 5.2.1 on 2025-06-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='member_id',
            new_name='member',
        ),
        migrations.AlterField(
            model_name='activity',
            name='polyline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
