# Generated by Django 5.2.3 on 2025-06-29 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('members', '0005_alter_section_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-datetime'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='type',
        ),
        migrations.AddField(
            model_name='activity',
            name='sport_type',
            field=models.CharField(choices=[('AlpineSki', 'Alpine Ski'), ('BackcountrySki', 'Backcountry Ski'), ('Badminton', 'Badminton'), ('Canoeing', 'Canoeing'), ('Crossfit', 'Crossfit'), ('EBikeRide', 'E-Bike Ride'), ('Elliptical', 'Elliptical'), ('EMountainBikeRide', 'E-Mountain Bike Ride'), ('Golf', 'Golf'), ('GravelRide', 'Gravel Ride'), ('Handcycle', 'Handcycle'), ('HighIntensityIntervalTraining', 'High Intensity Interval Training'), ('Hike', 'Hike'), ('IceSkate', 'Ice Skate'), ('InlineSkate', 'Inline Skate'), ('Kayaking', 'Kayaking'), ('Kitesurf', 'Kitesurf'), ('MountainBikeRide', 'Mountain Bike Ride'), ('NordicSki', 'Nordic Ski'), ('Pickleball', 'Pickleball'), ('Pilates', 'Pilates'), ('Racquetball', 'Racquetball'), ('Ride', 'Ride'), ('RockClimbing', 'Rock Climbing'), ('RollerSki', 'Roller Ski'), ('Rowing', 'Rowing'), ('Run', 'Run'), ('Sail', 'Sail'), ('Skateboard', 'Skateboard'), ('Snowboard', 'Snowboard'), ('Snowshoe', 'Snowshoe'), ('Soccer', 'Soccer'), ('Squash', 'Squash'), ('StairStepper', 'Stair Stepper'), ('StandUpPaddling', 'Stand Up Paddling'), ('Surfing', 'Surfing'), ('Swim', 'Swim'), ('TableTennis', 'Table Tennis'), ('Tennis', 'Tennis'), ('TrailRun', 'Trail Run'), ('Velomobile', 'Velomobile'), ('VirtualRide', 'Virtual Ride'), ('VirtualRow', 'Virtual Row'), ('VirtualRun', 'Virtual Run'), ('Walk', 'Walk'), ('WeightTraining', 'Weight Training'), ('Wheelchair', 'Wheelchair'), ('Windsurf', 'Windsurf'), ('Workout', 'Workout'), ('Yoga', 'Yoga')], default='Run', help_text='The type of activity (e.g., Run, Ride, Walk).', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_id',
            field=models.BigIntegerField(help_text='The Strava activity ID for the activity.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='datetime',
            field=models.DateTimeField(help_text='The date and time that the activity started.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=models.FloatField(blank=True, default=0, help_text='The distance (in miles) of the activity (if applicable).'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='elapsed_time',
            field=models.IntegerField(blank=True, default=0, help_text='The total elapsed time of the activity, in minutes. Includes pauses.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='elevation_gain',
            field=models.FloatField(blank=True, default=0, help_text='The total elevation gain of the activity, in feet (if applicable).'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='manual',
            field=models.BooleanField(help_text='Whether the activity was entered manually.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='member',
            field=models.ForeignKey(help_text='The member that the activity belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='members.member'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='minutes',
            field=models.IntegerField(blank=True, default=0, help_text='The duration of the activity, in minutes.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(help_text="The name of the activity (e.g., 'Morning Run').", max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='polyline',
            field=models.TextField(blank=True, help_text='The encoded polyline representing the GPS route (if applicable).', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='private',
            field=models.BooleanField(help_text='Whether the activity is marked as private.'),
        ),
    ]
