# Generated by Django 5.2.1 on 2026-05-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_svg_view_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when the activity is soft-deleted (removed from Strava or access revoked).', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='deletion_reason',
            field=models.CharField(blank=True, choices=[('strava_delete', 'Deleted on Strava'), ('strava_deauth', 'Strava access revoked'), ('sync_missing', 'Not found during sync')], default='', help_text='Why this activity was soft-deleted.', max_length=20),
        ),
    ]
