# Generated by Django 5.2.3 on 2025-07-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_options_remove_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='activity_maps/'),
        ),
    ]
