# Generated by Django 5.2.3 on 2025-07-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_map_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='polyline',
            field=models.TextField(blank=True, default='', help_text='The encoded polyline representing the GPS route (if applicable).'),
        ),
    ]
