# Generated by Django 5.2.1 on 2026-06-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_soft_delete_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='deletion_reason',
            field=models.CharField(blank=True, choices=[('strava_delete', 'Deleted on Strava'), ('strava_deauth', 'Strava access revoked'), ('sync_missing', 'Not found during sync'), ('date_out_of_range', 'Date outside all competition periods')], default='', help_text='Why this activity was soft-deleted.', max_length=20),
        ),
    ]
