# Generated by Django 5.2.3 on 2025-06-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpreferences',
            name='nickname',
            field=models.CharField(blank=True, help_text="The member's chosen nickname, to be displayed instead of their roster name.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='memberpreferences',
            name='preferred_email',
            field=models.EmailField(blank=True, help_text="The member's preferred contact email.", max_length=254, null=True),
        ),
    ]
