# Generated by Django 5.2.1 on 2026-05-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpreferences',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='system', help_text="The member's preferred theme (light, dark, or system default).", max_length=20),
        ),
    ]
