# Generated by Django 5.2.3 on 2025-06-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_memberpreferences_nickname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='memberpreferences',
            options={'verbose_name': 'Member Preferences', 'verbose_name_plural': 'Member Preferences'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='stravaauth',
            options={'verbose_name': 'Strava Authorization', 'verbose_name_plural': 'Strava Authorizations'},
        ),
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-safe version of the section name, used in links. Auto-generated if left blank.', unique=True),
        ),
    ]
