# Generated by Django 5.2.1 on 2025-05-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member',
            new_name='strava_auth',
        ),
        migrations.AlterField(
            model_name='member',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
