# Generated by Django 5.2.1 on 2026-05-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_memberpreferences_theme_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('section', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField(choices=[(1, 'Rookie'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year+')])),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Roster Request',
                'verbose_name_plural': 'Roster Requests',
                'db_table': 'roster_request',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.RemoveField(
            model_name='memberpreferences',
            name='theme_preference',
        ),
    ]
