# Generated by Django 5.2.1 on 2025-05-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_member_member_strava_auth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravaauth',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stravaauth',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stravaauth',
            name='scope',
            field=models.TextField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='stravaauth',
            name='token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
