# Generated by Django 5.2.3 on 2025-06-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_options_alter_memberpreferences_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-safe version of the section name, used in links. Auto-generated if left blank.', null=True),
        ),
    ]
