# Generated by Django 5.2.1 on 2026-05-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rosterrequest_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RosterRequest',
        ),
    ]
