# Generated by Django 5.2.1 on 2026-05-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_rosterrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaauth',
            name='revoked_at',
            field=models.DateTimeField(blank=True, help_text='Set when the member revokes Strava access via webhook.', null=True),
        ),
    ]
