# Generated by Django 5.2.1 on 2025-06-27 15:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_stravaauth_access_token_and_more'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='sections.section'),
        ),
        migrations.RemoveField(
            model_name='member',
            name='strava_auth',
        ),
        migrations.AddField(
            model_name='stravaauth',
            name='member',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='strava_auth', to='members.member'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stravaauth',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stravaauth',
            name='refresh_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stravaauth',
            name='scope',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stravaauth',
            name='token_expires',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='MemberPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('preferred_email', models.EmailField(max_length=254)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberWeeklyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('minutes', models.PositiveIntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_points', to='members.member')),
            ],
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
