# Generated by Django 5.2.1 on 2025-07-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_section_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='member',
        ),
        migrations.AlterModelTable(
            name='memberpreferences',
            table='member_preferences',
        ),
        migrations.AlterModelTable(
            name='section',
            table='section',
        ),
        migrations.AlterModelTable(
            name='stravaauth',
            table='strava_auth',
        ),
    ]
