# Generated by Django 5.2.1 on 2026-06-02 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_stravaauth_revoked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_independent',
            field=models.BooleanField(default=False, help_text='If True, this member is not part of any section and is excluded from the roster and section scoring.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='section',
            field=models.ForeignKey(blank=True, help_text='The section that the member belongs to. Null for independent members.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.section'),
        ),
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Rookie'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year+')], help_text="The member's year in band. Null for independent members.", null=True),
        ),
    ]
