# Generated by Django 5.2.1 on 2026-06-08 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_add_is_independent_make_section_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberWeeklyScore',
            fields=[
            ],
            options={
                'verbose_name': 'Member Weekly Score',
                'verbose_name_plural': 'Member Weekly Scores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('members.member',),
        ),
    ]
