# Generated by Django 5.2.1 on 2026-05-18 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('members', '0001_initial'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rotation', models.PositiveSmallIntegerField(default=0, help_text='Rotation in degrees (0, 45, 90, ..., 315).')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('anonymous', 'Anonymous'), ('private', 'Private')], default='public', max_length=20)),
                ('is_withdrawn', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, help_text='The activity whose route is used as the artwork.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='art_submissions', to='activities.activity')),
                ('member', models.ForeignKey(help_text='The member who submitted this artwork.', on_delete=django.db.models.deletion.CASCADE, related_name='art_submissions', to='members.member')),
                ('period', models.ForeignKey(help_text='The competition period this submission is for.', on_delete=django.db.models.deletion.CASCADE, related_name='art_submissions', to='metrics.competitionperiod')),
            ],
            options={
                'db_table': 'art_submission',
                'unique_together': {('member', 'period')},
            },
        ),
        migrations.CreateModel(
            name='ArtWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(help_text="The art theme for this period (e.g. 'Loop', 'Letter M').", max_length=100)),
                ('period', models.OneToOneField(help_text='The competition period this art challenge covers.', on_delete=django.db.models.deletion.CASCADE, related_name='art_week', to='metrics.competitionperiod')),
            ],
            options={
                'db_table': 'art_week',
            },
        ),
        migrations.CreateModel(
            name='ArtLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_likes', to='members.member')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='art.artsubmission')),
            ],
            options={
                'db_table': 'art_like',
                'unique_together': {('submission', 'member')},
            },
        ),
    ]
