# Generated by Django 5.2.1 on 2026-05-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artsubmission',
            name='bg_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='artsubmission',
            name='stroke_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='artsubmission',
            name='stroke_width',
            field=models.FloatField(default=2.8),
        ),
    ]
