# Generated by Django 5.2.1 on 2026-05-19 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_artsubmission_bg_color_artsubmission_stroke_color_and_more'),
        ('metrics', '0002_add_rank_score_to_section_period_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsubmission',
            name='period',
            field=models.ForeignKey(blank=True, help_text='The competition period this submission is for. Null for open (non-weekly) submissions.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='art_submissions', to='metrics.competitionperiod'),
        ),
    ]
