"""
Django settings for ummbsummer project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from dotenv import load_dotenv, find_dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(find_dotenv())

# Django secret key
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')


STATIC_ROOT = '/var/www/ummbsummer/static'


# With DEBUG = True (development):
#   Backend URL:  http://localhost:8000
#   Frontend URL: http://localhost:5173
# 
# With DEBUG = False (production):
#   Backend/Frontend URL: https://ummbsummer.com 
DEBUG = True

LOCAL_BACKEND_URL = 'http://localhost:8000'
LOCAL_FRONTEND_URL = 'http://localhost:5173'

PRODUCTION_URL = 'https://ummbsummer.com'

BASE_BACKEND_URL = LOCAL_BACKEND_URL if DEBUG else PRODUCTION_URL
BASE_FRONTEND_URL = LOCAL_FRONTEND_URL if DEBUG else PRODUCTION_URL

ALLOWED_HOSTS = ['localhost'] if DEBUG else ['ummbsummer.com']

CORS_ALLOWED_ORIGINS = [LOCAL_FRONTEND_URL] if DEBUG else [PRODUCTION_URL]
CSRF_TRUSTED_ORIGINS = [LOCAL_FRONTEND_URL] if DEBUG else [PRODUCTION_URL]

CORS_ALLOW_CREDENTIALS = True

# TODO: Check if this is needed
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

GOOGLE_AUTH = {
    'CLIENT_ID': os.getenv('GOOGLE_CLIENT_ID'),
    'CLIENT_SECRET': os.getenv('GOOGLE_CLIENT_SECRET'),
    'REDIRECT_URI': f'{BASE_BACKEND_URL}/api/auth/callback',
    'HD': 'umn.edu',
    'SCOPES': ['openid', 'https://www.googleapis.com/auth/userinfo.email']
}

STRAVA_AUTH = {
    
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'members',
    'activities',
    'strava',
    'google_auth',
    'metrics',
    'art',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication'
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated'
    ]    
}


ROOT_URLCONF = 'ummbsummer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ummbsummer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DATABASE_NAME"),
        'USER': os.getenv("DATABASE_USER"),
        'PASSWORD': os.getenv("DATABASE_PASSWORD"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
